version: '3'
services:
  xeyes:
    build: .
    image: xeyes
    container_name: xeyes1
    privileged: true
    environment:
        DISPLAY: $DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix 
