services:
  samplebrain:
    build: .
    image: samplebrain 
    container_name: samplebrain1
    privileged: true
    environment:
      - DISPLAY=host.docker.internal:0
      - PULSE_SERVER=docker.for.mac.localhost
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix 
      - ~/.config/pulse:/root/.config/pulse